// SPDX-License-Identifier: GPL-2.0-or-later
// pnpm golden:examples [--report] [file.txt ...]
// Runs every bundled upstream example in this port and compares it with fixtures/examples/
// (recorded from the reference by record-examples.ts). --report rewrites docs/EXAMPLES.md and the
// list of passing examples that tools/golden/src/examples.test.ts holds the port to.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { EXAMPLE_FIXTURE_DIR, exampleFiles, fixtureName, parseExampleFixture } from './examples.ts';
import { checkExample } from './examples-run.ts';
import { REPO_ROOT } from './manifest.ts';
import type { ExampleResult } from './examples.ts';

export const REPORT_PATH = join(REPO_ROOT, 'docs/EXAMPLES.md');
export const PASSING_PATH = join(REPO_ROOT, 'tools/golden/examples-passing.txt');

export function checkAll(files: string[]): ExampleResult[] {
  return files.map((file) =>
    checkExample(
      parseExampleFixture(readFileSync(join(EXAMPLE_FIXTURE_DIR, fixtureName(file)), 'utf8')),
    ),
  );
}

const cell = (s: string): string => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function formatReport(results: ExampleResult[]): string {
  const pass = results.filter((r) => r.status === 'pass').length;
  const saves = results.filter((r) => r.sameSave).length;
  const pct = (n: number): string => ((100 * n) / results.length).toFixed(1);
  const lines = [
    '# Upstream examples: pass rate',
    '',
    'Generated by `pnpm golden:examples --report`; do not edit by hand.',
    '',
    `Every bundled upstream example (${results.length} files) runs in this port and in the reference`,
    'build (`fixtures/examples/`, recorded by `pnpm golden:record-examples`). An example passes when',
    'the topology (node numbering of every element), the stop state and every node voltage at',
    `steps ${'1, 2, 5, 10, 20, 50, 100, 200, 500 and 1000'} match within the golden tolerances`,
    '(tools/golden/README.md). "Same save" means our XML save after loading is byte for byte',
    "upstream's.",
    '',
    `**Pass: ${pass} of ${results.length} (${pct(pass)}%).** Same save: ${saves} (${pct(saves)}%).`,
    '',
    'Failures are listed in [DEVIATIONS.md](DEVIATIONS.md) with their causes.',
    '',
    '| Example | Result | Same save | First difference |',
    '| ------- | ------ | --------- | ---------------- |',
  ];
  for (const r of results)
    lines.push(
      `| ${r.file} | ${r.status} | ${r.sameSave ? 'yes' : 'no'} | ${cell(r.reason ?? '')} |`,
    );
  return lines.join('\n') + '\n';
}

function main(): void {
  const args = process.argv.slice(2);
  const report = args.includes('--report');
  const picked = args.filter((a) => !a.startsWith('--'));
  const files = picked.length > 0 ? picked : exampleFiles();
  const start = Date.now();
  const results = checkAll(files);
  for (const r of results)
    if (picked.length > 0 || r.status !== 'pass')
      console.log(`${r.status.padEnd(5)} ${r.file}${r.reason ? `: ${r.reason}` : ''}`);
  const pass = results.filter((r) => r.status === 'pass').length;
  const saves = results.filter((r) => r.sameSave).length;
  console.log(
    `${pass}/${results.length} pass (${((100 * pass) / results.length).toFixed(1)}%), ` +
      `${saves} save identically, ${((Date.now() - start) / 1000).toFixed(1)} s`,
  );
  if (report && picked.length === 0) {
    writeFileSync(REPORT_PATH, formatReport(results));
    writeFileSync(
      PASSING_PATH,
      results
        .filter((r) => r.status === 'pass')
        .map((r) => r.file)
        .join('\n') + '\n',
    );
    console.log(`wrote ${REPORT_PATH} and ${PASSING_PATH}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) main();
