// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Perun contributors

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';

function listFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...listFiles(p));
    else out.push(p);
  }
  return out;
}

/**
 * Writes `sw.js`, the service worker that makes the app work offline (PLAN.md Phase 9): it
 * caches every file of the build on install (the app, fonts, the example circuits and the
 * licenses) and serves them from the cache. Translations are cached when first used, so only the
 * languages someone picks are downloaded. The cache name carries a hash of all the files, so a
 * new build is a new worker; the app offers to reload into it (src/pwa.ts).
 */
export function serviceWorker(): Plugin {
  let config: ResolvedConfig;
  return {
    name: 'circuitjs-service-worker',
    apply: 'build',
    configResolved(c) {
      config = c;
    },
    writeBundle() {
      const outDir = config.build.outDir;
      const files = listFiles(outDir)
        .map((p) => relative(outDir, p).split(sep).join('/'))
        .filter((f) => f !== 'sw.js' && !f.endsWith('.map'))
        .sort();
      const precache = files.filter((f) => !LAZY.test(f));
      const hash = createHash('sha256');
      for (const f of files) {
        hash.update(f);
        hash.update(readFileSync(join(outDir, f)));
      }
      // the worker's own code too, so a fixed worker never shares a cache with the one it replaces
      hash.update(workerSource('', precache));
      const version = hash.digest('hex').slice(0, 12);
      writeFileSync(join(outDir, 'sw.js'), workerSource(version, precache));
    },
  };
}

/** Files cached on first use instead of on install: the string catalogs. */
const LAZY = /^locale_[a-z-]+\.txt$/;

function workerSource(version: string, files: string[]): string {
  const LAZY_IN_WORKER = LAZY.toString();
  return `// Perun service worker (generated by vite-plugin-sw.ts). GPL-2.0-or-later.
const CACHE = 'perun-${version}';
const FILES = ${JSON.stringify(['./', ...files])};

// Fetch past the browser's HTTP cache: GitHub Pages lets it keep index.html for 10 minutes, and a
// worker that cached the old page with this build's files would load scripts the server no longer
// has (a white screen). Then check the page names only files of this build; if not (a server or
// CDN still serving the old page), fail the install, so the working version stays and the next
// visit tries again.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      await cache.addAll(FILES.map((f) => new Request(new URL(f, self.registration.scope), { cache: 'reload' })));
      const shell = await cache.match(new URL('./', self.registration.scope));
      const html = shell ? await shell.text() : '';
      const refs = html.match(/assets[/][^"'?#)<> ]+/g) || [];
      if (html === '' || refs.some((r) => !FILES.includes(r))) {
        await caches.delete(CACHE);
        throw new Error('the page does not match this build yet');
      }
    }),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => (k.startsWith('perun-') || k.startsWith('circuitjs-next-')) && k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

// the page asks a waiting worker to take over when the user accepts the update
self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  // every page of the app is the app shell; its query (?cct=, ?ctz=, ?theme=) is read by the app
  const key = req.mode === 'navigate' ? new URL('./', self.registration.scope).href : req;
  event.respondWith(
    caches.open(CACHE).then((cache) =>
      // ignoreVary: servers vary on Origin, which module scripts send and the install didn't
      cache.match(key, { ignoreSearch: req.mode === 'navigate', ignoreVary: true }).then(
        (hit) =>
          hit ||
          fetch(req).then((res) => {
            // a language, once used, works offline too
            if (res.ok && ${LAZY_IN_WORKER}.test(url.pathname.split('/').pop())) void cache.put(req, res.clone());
            return res;
          }),
      ),
    ),
  );
});
`;
}
