// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 circuitjs-next contributors

/*
 * Writes docs/theme.schema.json and the key reference in docs/THEMES.md from the theme package's
 * zod schema, so the docs can't drift from what the app accepts. `pnpm theme:docs` runs it;
 * generate.test.ts fails when the committed files are out of date.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import { BUILTIN_THEMES, themeJsonSchema } from '../../../packages/theme/src/index.ts';

const DOCS = fileURLToPath(new URL('../../../docs/', import.meta.url));
export const SCHEMA_PATH = DOCS + 'theme.schema.json';
export const THEMES_MD = DOCS + 'THEMES.md';
const START = '<!-- keys:start (generated by pnpm theme:docs) -->';
const END = '<!-- keys:end -->';

interface Node {
  type?: string;
  description?: string;
  properties?: Record<string, Node>;
  items?: Node;
  enum?: string[];
  const?: unknown;
  minimum?: number;
  maximum?: number;
  minItems?: number;
  maxItems?: number;
  maxLength?: number;
}

/** Format as `pnpm format` would, so the generated files pass format:check. */
async function pretty(text: string, filepath: string): Promise<string> {
  const options = (await prettier.resolveConfig(filepath)) ?? {};
  return prettier.format(text, { ...options, filepath });
}

export function schemaText(): Promise<string> {
  return pretty(JSON.stringify(themeJsonSchema(), null, 2), SCHEMA_PATH);
}

function typeOf(n: Node): string {
  if (n.const !== undefined) return `\`${JSON.stringify(n.const)}\``;
  if (n.enum) return n.enum.map((e) => `\`${e}\``).join(', ');
  if (n.type === 'number') return `number, ${n.minimum} to ${n.maximum}`;
  if (n.type === 'array') return `colors, ${n.minItems} to ${n.maxItems}`;
  if (n.type === 'string')
    return n.maxLength === 64 ? 'color' : n.maxLength === 40 ? 'built-in id' : 'text';
  return n.type ?? '';
}

/** Example value: the Dark built-in's. */
function example(path: string[]): string {
  let v: unknown = BUILTIN_THEMES['dark'];
  for (const p of path) v = (v as Record<string, unknown> | undefined)?.[p];
  if (v === undefined) return '';
  const s = JSON.stringify(v);
  return '`' + (s.length > 48 ? s.slice(0, 45) + '...' : s) + '`';
}

/** The markdown table of every key. */
export function keyTable(): string {
  const root = themeJsonSchema() as Node;
  const rows: string[] = ['| Key | Type | Dark | Meaning |', '| --- | --- | --- | --- |'];
  const walk = (n: Node, path: string[]): void => {
    for (const [k, child] of Object.entries(n.properties ?? {})) {
      const p = [...path, k];
      if (child.type === 'object') {
        rows.push(`| **${p.join('.')}** | | | ${child.description ?? ''} |`);
        walk(child, p);
      } else {
        rows.push(
          `| \`${p.join('.')}\` | ${typeOf(child)} | ${example(p)} | ${(child.description ?? '').replaceAll('|', '\\|')} |`,
        );
      }
    }
  };
  walk(root, []);
  return rows.join('\n');
}

export function themesMdText(current: string): Promise<string> {
  const a = current.indexOf(START);
  const b = current.indexOf(END);
  if (a < 0 || b < a) throw new Error(`docs/THEMES.md lacks the ${START} ... ${END} markers`);
  return pretty(
    current.slice(0, a + START.length) + '\n\n' + keyTable() + '\n\n' + current.slice(b),
    THEMES_MD,
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(SCHEMA_PATH, await schemaText());
  writeFileSync(THEMES_MD, await themesMdText(readFileSync(THEMES_MD, 'utf8')));
  console.log('wrote docs/theme.schema.json and the key table in docs/THEMES.md');
}
